import type { Metadata } from "next";

import "./globals.css";
import MainHeader from "@/components/header/MainHeader";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-sans"
      >
        <div className="fixed z-50 top-0 w-full">
          <MainHeader></MainHeader>
        </div>
        {children}
      </body>
    </html>
  );
}
